all:
	g++ auto.cpp -std=c++0x -o auto.o -O3 -I /usr/local/include/boost_1_56_0/
	g++ manual.cpp -std=c++0x -o manual.o -O3 -I /usr/local/include/boost_1_56_0/

auto:
	g++ auto.cpp -std=c++0x -o auto.o -O3 -I /usr/local/include/boost_1_56_0/

manual:
	g++ manual.cpp -std=c++0x -o manual.o -O3 -I /usr/local/include/boost_1_56_0/

clean:
	rm -r *.o

